import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faArrowRight,
  faArrowDown,
  faTv,
  faEnvelope,
  faPhone,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faUser,
  faSearch,
  faHome,
  faGlobe,
  faUsers,
  faHandshake,
  faLightbulb,
  faBook,
  faGraduationCap,
  faBriefcase,
  faMapMarkerAlt,
  faCalendar,
  faPlay,
  faPause,
  faVolumeUp,
  faVolumeMute,
  faMasksTheater,
  faLeaf,
  faLocationDot,
  faFilter,
  faTags,
  faFlag,
  faTag,
  faPlus,
  faHeart,
  faEye,
  faThumbsDown,
  faComment,
  faShare,
  faCalendarXmark,
  faSliders,
  faSpinner,
  faPaperPlane,
  faFileCircleXmark,
  faComments,
  faCommentSlash,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons'
import {
  faFacebook,
  faTwitter,
  faLinkedin,
  faInstagram,
  faYoutube,
  faWhatsapp,
} from '@fortawesome/free-brands-svg-icons'

// Prevent auto CSS injection
config.autoAddCss = false

// Add icons to library
library.add(
  faArrowRight,
  faArrowDown,
  faTv,
  faEnvelope,
  faPhone,
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faUser,
  faSearch,
  faHome,
  faGlobe,
  faUsers,
  faHandshake,
  faLightbulb,
  faBook,
  faGraduationCap,
  faBriefcase,
  faMapMarkerAlt,
  faCalendar,
  faPlay,
  faPause,
  faVolumeUp,
  faVolumeMute,
  faMasksTheater,
  faLeaf,
  faLocationDot,
  faFilter,
  faTags,
  faFlag,
  faTag,
  faPlus,
  faHeart,
  faEye,
  faThumbsDown,
  faComment,
  faShare,
  faCalendarXmark,
  faSliders,
  faSpinner,
  faPaperPlane,
  faFileCircleXmark,
  faComments,
  faCommentSlash,
  faTriangleExclamation,
  faFacebook,
  faTwitter,
  faLinkedin,
  faInstagram,
  faYoutube,
  faWhatsapp
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon)
})
