-- ════════════════════════════════════════════════════════════════════════════
-- AFRICANS-WORLD — Seed : tous les pays du monde (hors Afrique déjà seedée)
-- ════════════════════════════════════════════════════════════════════════════
-- Complète shared.pays avec les pays d'Europe, d'Asie, des Amériques et d'Océanie
-- afin que le sélecteur « Territoires ciblés » du marché propose le monde entier.
--
-- Idempotent : ON CONFLICT (code_iso2) DO NOTHING
--   → les 54 États africains (30_seed_pays_africains.sql) et la diaspora déjà
--     présente (France, Canada…) ne sont jamais modifiés.
-- Doit être chargé APRÈS 30_seed_pays_africains.sql.
-- ════════════════════════════════════════════════════════════════════════════

INSERT INTO shared.pays (nom, code_iso2, code_iso3, indicatif_tel, capitale, continent) VALUES
    -- ── Europe ──────────────────────────────────────────────────────────────
    ('Albanie',                            'AL', 'ALB', '+355',  'Tirana',               'Europe'),
    ('Allemagne',                          'DE', 'DEU', '+49',   'Berlin',               'Europe'),
    ('Andorre',                            'AD', 'AND', '+376',  'Andorre-la-Vieille',   'Europe'),
    ('Autriche',                           'AT', 'AUT', '+43',   'Vienne',               'Europe'),
    ('Belgique',                           'BE', 'BEL', '+32',   'Bruxelles',            'Europe'),
    ('Biélorussie',                        'BY', 'BLR', '+375',  'Minsk',                'Europe'),
    ('Bosnie-Herzégovine',                 'BA', 'BIH', '+387',  'Sarajevo',             'Europe'),
    ('Bulgarie',                           'BG', 'BGR', '+359',  'Sofia',                'Europe'),
    ('Chypre',                             'CY', 'CYP', '+357',  'Nicosie',              'Europe'),
    ('Croatie',                            'HR', 'HRV', '+385',  'Zagreb',               'Europe'),
    ('Danemark',                           'DK', 'DNK', '+45',   'Copenhague',           'Europe'),
    ('Espagne',                            'ES', 'ESP', '+34',   'Madrid',               'Europe'),
    ('Estonie',                            'EE', 'EST', '+372',  'Tallinn',              'Europe'),
    ('Finlande',                           'FI', 'FIN', '+358',  'Helsinki',             'Europe'),
    ('Grèce',                              'GR', 'GRC', '+30',   'Athènes',              'Europe'),
    ('Hongrie',                            'HU', 'HUN', '+36',   'Budapest',             'Europe'),
    ('Irlande',                            'IE', 'IRL', '+353',  'Dublin',               'Europe'),
    ('Islande',                            'IS', 'ISL', '+354',  'Reykjavik',            'Europe'),
    ('Italie',                             'IT', 'ITA', '+39',   'Rome',                 'Europe'),
    ('Kosovo',                             'XK', 'XKX', '+383',  'Pristina',             'Europe'),
    ('Lettonie',                           'LV', 'LVA', '+371',  'Riga',                 'Europe'),
    ('Liechtenstein',                      'LI', 'LIE', '+423',  'Vaduz',                'Europe'),
    ('Lituanie',                           'LT', 'LTU', '+370',  'Vilnius',              'Europe'),
    ('Luxembourg',                         'LU', 'LUX', '+352',  'Luxembourg',           'Europe'),
    ('Macédoine du Nord',                  'MK', 'MKD', '+389',  'Skopje',               'Europe'),
    ('Malte',                              'MT', 'MLT', '+356',  'La Valette',           'Europe'),
    ('Moldavie',                           'MD', 'MDA', '+373',  'Chișinău',             'Europe'),
    ('Monaco',                             'MC', 'MCO', '+377',  'Monaco',               'Europe'),
    ('Monténégro',                         'ME', 'MNE', '+382',  'Podgorica',            'Europe'),
    ('Norvège',                            'NO', 'NOR', '+47',   'Oslo',                 'Europe'),
    ('Pays-Bas',                           'NL', 'NLD', '+31',   'Amsterdam',            'Europe'),
    ('Pologne',                            'PL', 'POL', '+48',   'Varsovie',             'Europe'),
    ('Portugal',                           'PT', 'PRT', '+351',  'Lisbonne',             'Europe'),
    ('Roumanie',                           'RO', 'ROU', '+40',   'Bucarest',             'Europe'),
    ('Royaume-Uni',                        'GB', 'GBR', '+44',   'Londres',              'Europe'),
    ('Russie',                             'RU', 'RUS', '+7',    'Moscou',               'Europe'),
    ('Saint-Marin',                        'SM', 'SMR', '+378',  'Saint-Marin',          'Europe'),
    ('Serbie',                             'RS', 'SRB', '+381',  'Belgrade',             'Europe'),
    ('Slovaquie',                          'SK', 'SVK', '+421',  'Bratislava',           'Europe'),
    ('Slovénie',                           'SI', 'SVN', '+386',  'Ljubljana',            'Europe'),
    ('Suède',                              'SE', 'SWE', '+46',   'Stockholm',            'Europe'),
    ('Suisse',                             'CH', 'CHE', '+41',   'Berne',                'Europe'),
    ('Tchéquie',                           'CZ', 'CZE', '+420',  'Prague',               'Europe'),
    ('Ukraine',                            'UA', 'UKR', '+380',  'Kyiv',                 'Europe'),
    ('Vatican',                            'VA', 'VAT', '+379',  'Cité du Vatican',      'Europe'),
    -- ── Asie ────────────────────────────────────────────────────────────────
    ('Afghanistan',                        'AF', 'AFG', '+93',   'Kaboul',               'Asie'),
    ('Arabie saoudite',                    'SA', 'SAU', '+966',  'Riyad',                'Asie'),
    ('Arménie',                            'AM', 'ARM', '+374',  'Erevan',               'Asie'),
    ('Azerbaïdjan',                        'AZ', 'AZE', '+994',  'Bakou',                'Asie'),
    ('Bahreïn',                            'BH', 'BHR', '+973',  'Manama',               'Asie'),
    ('Bangladesh',                         'BD', 'BGD', '+880',  'Dacca',                'Asie'),
    ('Bhoutan',                            'BT', 'BTN', '+975',  'Thimphou',             'Asie'),
    ('Birmanie (Myanmar)',                 'MM', 'MMR', '+95',   'Naypyidaw',            'Asie'),
    ('Brunei',                             'BN', 'BRN', '+673',  'Bandar Seri Begawan',  'Asie'),
    ('Cambodge',                           'KH', 'KHM', '+855',  'Phnom Penh',           'Asie'),
    ('Chine',                              'CN', 'CHN', '+86',   'Pékin',                'Asie'),
    ('Corée du Nord',                      'KP', 'PRK', '+850',  'Pyongyang',            'Asie'),
    ('Corée du Sud',                       'KR', 'KOR', '+82',   'Séoul',                'Asie'),
    ('Émirats arabes unis',               'AE', 'ARE', '+971',  'Abou Dabi',            'Asie'),
    ('Géorgie',                            'GE', 'GEO', '+995',  'Tbilissi',             'Asie'),
    ('Inde',                               'IN', 'IND', '+91',   'New Delhi',            'Asie'),
    ('Indonésie',                          'ID', 'IDN', '+62',   'Jakarta',              'Asie'),
    ('Irak',                               'IQ', 'IRQ', '+964',  'Bagdad',               'Asie'),
    ('Iran',                               'IR', 'IRN', '+98',   'Téhéran',              'Asie'),
    ('Israël',                             'IL', 'ISR', '+972',  'Jérusalem',            'Asie'),
    ('Japon',                              'JP', 'JPN', '+81',   'Tokyo',                'Asie'),
    ('Jordanie',                           'JO', 'JOR', '+962',  'Amman',                'Asie'),
    ('Kazakhstan',                         'KZ', 'KAZ', '+7',    'Astana',               'Asie'),
    ('Kirghizistan',                       'KG', 'KGZ', '+996',  'Bichkek',              'Asie'),
    ('Koweït',                             'KW', 'KWT', '+965',  'Koweït',               'Asie'),
    ('Laos',                               'LA', 'LAO', '+856',  'Vientiane',            'Asie'),
    ('Liban',                              'LB', 'LBN', '+961',  'Beyrouth',             'Asie'),
    ('Malaisie',                           'MY', 'MYS', '+60',   'Kuala Lumpur',         'Asie'),
    ('Maldives',                           'MV', 'MDV', '+960',  'Malé',                 'Asie'),
    ('Mongolie',                           'MN', 'MNG', '+976',  'Oulan-Bator',          'Asie'),
    ('Népal',                              'NP', 'NPL', '+977',  'Katmandou',            'Asie'),
    ('Oman',                               'OM', 'OMN', '+968',  'Mascate',              'Asie'),
    ('Ouzbékistan',                        'UZ', 'UZB', '+998',  'Tachkent',             'Asie'),
    ('Pakistan',                           'PK', 'PAK', '+92',   'Islamabad',            'Asie'),
    ('Palestine',                          'PS', 'PSE', '+970',  'Ramallah',             'Asie'),
    ('Philippines',                        'PH', 'PHL', '+63',   'Manille',              'Asie'),
    ('Qatar',                              'QA', 'QAT', '+974',  'Doha',                 'Asie'),
    ('Singapour',                          'SG', 'SGP', '+65',   'Singapour',            'Asie'),
    ('Sri Lanka',                          'LK', 'LKA', '+94',   'Colombo',              'Asie'),
    ('Syrie',                              'SY', 'SYR', '+963',  'Damas',                'Asie'),
    ('Tadjikistan',                        'TJ', 'TJK', '+992',  'Douchanbé',            'Asie'),
    ('Taïwan',                             'TW', 'TWN', '+886',  'Taipei',               'Asie'),
    ('Thaïlande',                          'TH', 'THA', '+66',   'Bangkok',              'Asie'),
    ('Timor oriental',                     'TL', 'TLS', '+670',  'Dili',                 'Asie'),
    ('Turkménistan',                       'TM', 'TKM', '+993',  'Achgabat',             'Asie'),
    ('Turquie',                            'TR', 'TUR', '+90',   'Ankara',               'Asie'),
    ('Vietnam',                            'VN', 'VNM', '+84',   'Hanoï',                'Asie'),
    ('Yémen',                              'YE', 'YEM', '+967',  'Sanaa',                'Asie'),
    -- ── Amérique du Nord, centrale & Caraïbes ────────────────────────────────
    ('États-Unis',                        'US', 'USA', '+1',    'Washington',           'Amérique du Nord'),
    ('Mexique',                            'MX', 'MEX', '+52',   'Mexico',               'Amérique du Nord'),
    ('Antigua-et-Barbuda',                 'AG', 'ATG', '+1268', 'Saint John''s',        'Amérique du Nord'),
    ('Bahamas',                            'BS', 'BHS', '+1242', 'Nassau',               'Amérique du Nord'),
    ('Barbade',                            'BB', 'BRB', '+1246', 'Bridgetown',           'Amérique du Nord'),
    ('Belize',                             'BZ', 'BLZ', '+501',  'Belmopan',             'Amérique du Nord'),
    ('Costa Rica',                         'CR', 'CRI', '+506',  'San José',             'Amérique du Nord'),
    ('Cuba',                               'CU', 'CUB', '+53',   'La Havane',            'Amérique du Nord'),
    ('Dominique',                          'DM', 'DMA', '+1767', 'Roseau',               'Amérique du Nord'),
    ('République dominicaine',             'DO', 'DOM', '+1809', 'Saint-Domingue',       'Amérique du Nord'),
    ('Salvador',                           'SV', 'SLV', '+503',  'San Salvador',         'Amérique du Nord'),
    ('Grenade',                            'GD', 'GRD', '+1473', 'Saint-Georges',        'Amérique du Nord'),
    ('Guatemala',                          'GT', 'GTM', '+502',  'Guatemala',            'Amérique du Nord'),
    ('Haïti',                              'HT', 'HTI', '+509',  'Port-au-Prince',       'Amérique du Nord'),
    ('Honduras',                           'HN', 'HND', '+504',  'Tegucigalpa',          'Amérique du Nord'),
    ('Jamaïque',                           'JM', 'JAM', '+1876', 'Kingston',             'Amérique du Nord'),
    ('Nicaragua',                          'NI', 'NIC', '+505',  'Managua',              'Amérique du Nord'),
    ('Panama',                             'PA', 'PAN', '+507',  'Panama',               'Amérique du Nord'),
    ('Saint-Christophe-et-Niévès',         'KN', 'KNA', '+1869', 'Basseterre',           'Amérique du Nord'),
    ('Sainte-Lucie',                       'LC', 'LCA', '+1758', 'Castries',             'Amérique du Nord'),
    ('Saint-Vincent-et-les-Grenadines',    'VC', 'VCT', '+1784', 'Kingstown',            'Amérique du Nord'),
    ('Trinité-et-Tobago',                  'TT', 'TTO', '+1868', 'Port-d''Espagne',      'Amérique du Nord'),
    -- ── Amérique du Sud ──────────────────────────────────────────────────────
    ('Argentine',                          'AR', 'ARG', '+54',   'Buenos Aires',         'Amérique du Sud'),
    ('Bolivie',                            'BO', 'BOL', '+591',  'Sucre',                'Amérique du Sud'),
    ('Brésil',                             'BR', 'BRA', '+55',   'Brasília',             'Amérique du Sud'),
    ('Chili',                              'CL', 'CHL', '+56',   'Santiago',             'Amérique du Sud'),
    ('Colombie',                           'CO', 'COL', '+57',   'Bogota',               'Amérique du Sud'),
    ('Équateur',                           'EC', 'ECU', '+593',  'Quito',                'Amérique du Sud'),
    ('Guyana',                             'GY', 'GUY', '+592',  'Georgetown',           'Amérique du Sud'),
    ('Paraguay',                           'PY', 'PRY', '+595',  'Asuncion',             'Amérique du Sud'),
    ('Pérou',                              'PE', 'PER', '+51',   'Lima',                 'Amérique du Sud'),
    ('Suriname',                           'SR', 'SUR', '+597',  'Paramaribo',           'Amérique du Sud'),
    ('Uruguay',                            'UY', 'URY', '+598',  'Montevideo',           'Amérique du Sud'),
    ('Venezuela',                          'VE', 'VEN', '+58',   'Caracas',              'Amérique du Sud'),
    -- ── Océanie ──────────────────────────────────────────────────────────────
    ('Australie',                          'AU', 'AUS', '+61',   'Canberra',             'Océanie'),
    ('Fidji',                              'FJ', 'FJI', '+679',  'Suva',                 'Océanie'),
    ('Kiribati',                           'KI', 'KIR', '+686',  'Tarawa',               'Océanie'),
    ('Îles Marshall',                      'MH', 'MHL', '+692',  'Majuro',               'Océanie'),
    ('Micronésie',                         'FM', 'FSM', '+691',  'Palikir',              'Océanie'),
    ('Nauru',                              'NR', 'NRU', '+674',  'Yaren',                'Océanie'),
    ('Nouvelle-Zélande',                   'NZ', 'NZL', '+64',   'Wellington',           'Océanie'),
    ('Palaos',                             'PW', 'PLW', '+680',  'Ngerulmud',            'Océanie'),
    ('Papouasie-Nouvelle-Guinée',          'PG', 'PNG', '+675',  'Port Moresby',         'Océanie'),
    ('Samoa',                              'WS', 'WSM', '+685',  'Apia',                 'Océanie'),
    ('Îles Salomon',                       'SB', 'SLB', '+677',  'Honiara',              'Océanie'),
    ('Tonga',                              'TO', 'TON', '+676',  'Nuku''alofa',          'Océanie'),
    ('Tuvalu',                             'TV', 'TUV', '+688',  'Funafuti',             'Océanie'),
    ('Vanuatu',                            'VU', 'VUT', '+678',  'Port-Vila',            'Océanie')
ON CONFLICT (code_iso2) DO NOTHING;
